### ISSUE TITLE
iaas list networks fails with json decoding error

### ISSUE THREAD

**Issue by MichaelEischer** [stackitcloud/stackit-sdk-go#929] opened 2024-10-15 14:01 UTC
Using `github.com/stackitcloud/stackit-sdk-go/services/iaas@0.12.0` the `iaasClient.ListNetworks(ctx, projectID).Execute()` method can yield the following error:
```
{
        StatusCode: 200,
        Body: "{\"items\":[{\"createdAt\":\"2024-10-15T12:08:40Z\",\"gateway\":\"10.0.1.1\",\"labels\":{},\"name\":\"e2e-97ctpww-network\",\"nameservers\":[\"1.1.1.1\",\"8.8.8.8\"],\"nameserversV6\":[],\"networkId\":\"12345678-1234-1234-1234-123456781234\",\"prefixes\":[\"10.0.1.0/25\"],\"prefixesV6\":[],\"publicIp\":\"123.123.123.123\",\"routed\":true,\"state\":\"CREATED\",\"updatedAt\":\"2024-10-15T12:08:43Z\"}",
        ErrorMessage: "json: cannot unmarshal string into Go struct field Network.items.gateway of type iaas.V1NetworkGateway",
        Model: nil,
}
```

The type `iaas.V1NetworkGateway` is an empty struct. According to the [api docs](https://docs.api.stackit.cloud/documentation/iaas/version/v1#tag/Network/operation/v1ListNetworksInProject) the type is `string or null (v1NetworkGateway)`.

**Comment by vicentepinto98** [comment] 2024-10-18 10:44
The issue is fixed in the latest version of the iaas module [v0.14.0](https://github.com/stackitcloud/stackit-sdk-go/releases/tag/services%2Fiaas%2Fv0.14.0)

**Closed by vicentepinto98** 2024-10-18 10:44 UTC
Labels: bug
